Templating improvement (#43)
* Bump up version under development
* Fix a bug in hadling space containing keys
* Fix a bug in key handling that contains spaces
* Make templating happen 'per-node-basis' (Issue #42)
* Make documents up to date.

diff --git a/jq-front b/jq-front
--- a/jq-front
+++ b/jq-front
@@ -44,9 +44,11 @@ function _remove_meta_nodes() {
   _content="$(cat "${_target}")"
   if [[ $(is_object "${_content}") == true ]]; then
     _cur="$(mktemp_with_content "$(cat "${_target}")")"
+    local _keys
+    IFS=$'\n' read -d '' -r -a _keys <<<"$(all_paths "${_content}" | grep '"$extends"$')"
     # Intentional single quote to find a keyword that starts with '$'
     # shellcheck disable=SC2016
-    for i in $(all_paths "${_content}" | grep '"$extends"$'); do
+    for i in "${_keys[@]}"; do
       local _next
       _next="$(mktemp_with_content "$(jq ".|del(${i})" "${_cur}")")"
       _cur="${_next}"
@@ -72,34 +74,46 @@ function _expand_nodelevel_inheritances() {
   local _path="${3}"
   local _cur
   local _in
+  local _keys
   _cur=$(mktemp_with_content '{}')
   debug "(begin:_expand_nodelevel_inheritances:1:${_target})"
   # Intentional single quote to find a keyword that starts with '$'
   # shellcheck disable=SC2016
-  for i in $(all_paths "$(cat "${_target}")" | grep '"$extends"$'); do
-    debug "->_expand_nodelevel_inheritances:2:${i})"
-    while IFS= read -r j; do
+  IFS=$'\n' read -d '' -r -a _keys <<<"$(all_paths "$(cat "${_target}")" | grep '"$extends"$')"
+  for i in "${_keys[@]}"; do
+    debug "->_expand_nodelevel_inheritances:2:i='${i}')"
+    local -a _extendeds
+    IFS=$'\n' read -d '' -r -a _extendeds <<<"$(jq -r -c "${i}[]" "${_target}")"
+    for j in "${_extendeds[@]}"; do
       local _next
       local _jj
-      debug "-->_expand_nodelevel_inheritances:3:${j})"
-      _jj="$(find_file_in_path "${j}" "${_path}")"
-      validate_jf_json "${_jj}" "${_validation_mode}" || abort "failed on validation"
       local _merged_piece
       local _p
-      _p="${i%.\"\$extends\"}"
       local _cur_content
+      local _tmp_content
+      debug "-->_expand_nodelevel_inheritances:3:j='${j}')"
+      _jj="$(find_file_in_path "${j}" "${_path}")"
+      debug "-->_expand_nodelevel_inheritances:4:resolved '${j}'->'${_jj}'"
+      validate_jf_json "${_jj}" "${_validation_mode}" || abort "failed on validation"
+      debug "-->_expand_nodelevel_inheritances:5:validated '${_jj}'"
+      _p="${i%.\"\$extends\"}"
       _cur_content="$(cat "${_cur}")"
+      debug "-->_expand_nodelevel_inheritances:6:merging nodes at '${_p}'"
       if [[ $(has_value_at "${_p}" "${_cur_content}") == true ]]; then
         local _cur_piece
         _cur_piece=$(mktemp_with_content "$(echo "${_cur_content}" | jq "${_p}")")
         _merged_piece=$(mktemp_with_content "$(_merge_object_nodes "${_cur_piece}" "${_jj}")")
       else
-        _merged_piece=${_jj}
+        _merged_piece="${_jj}"
       fi
-      _next=$(mktemp_with_content "$(jq -n "input | ${_p}=input" "${_cur}" "${_merged_piece}")") ||
-        abort "failed on node replacing; _cur=$(cat "${_cur}"); _merged_piece=$(cat "${_merged_piece}")"
+      debug "-->_expand_nodelevel_inheritances:7:merged"
+      _tmp_content="$(jq -n "input | ${_p}=input" "${_cur}" "${_merged_piece}")"
+      [[ $? == 0 ]] || abort "Failed to merge nodes:_p=${_p},_merged_piece=${_merged_piece}"
+      debug "-->_expand_nodelevel_inheritances:8:written:$?"
+      _next=$(mktemp_with_content "${_tmp_content}")
       _cur="${_next}"
-    done <<<"$(jq -r -c "${i}[]" "${_target}")"
+      debug "-->_expand_nodelevel_inheritances:9:trying:i=${i} on _target=${_target}"
+    done
   done
   debug "(end:_expand_nodelevel_inheritances:1)"
   jq -r -c . "${_cur}"
@@ -114,6 +128,97 @@ function _validate_jf_json_with() {
   } || {
     quit "Validation by ajv for '${_in}' was failed:\n${_out}"
   }
+}
+
+function _render_text_node() {
+  local _node_value="${1}"
+  local _path="${2}"
+  local _mode="raw"
+  local _quote="yes"
+  local _body
+  local _ret
+  debug "rendering"
+  if [[ "${_node_value}" == template:* || "${_node_value}" == raw:* ]]; then
+    _mode="${_node_value%%:*}"
+    _body="${_node_value#*:}"
+    if [[ "${_body}" == object:* || "${_body}" == array:* ||
+    "${_body}" == string:* || "${_body}" == number:* || "${_body}" == boolean:* ]] \
+      ; then
+      if [[ "${_body}" != string:* ]]; then
+        _quote="no"
+      fi
+      _body="${_body#*:}"
+    fi
+  else
+    _body="${_node_value}"
+  fi
+
+  if [[ "${_mode}" == "template" ]]; then
+    _ret=$(eval echo "${_body}")
+  elif [[ "${_mode}" == "raw" ]]; then
+    _ret="${_body}"
+  fi
+  debug "rendered:_mode='${_mode}'"
+  if [[ "${_quote}" == yes ]]; then
+    echo "\"${_ret}\""
+  else
+    echo "${_ret}"
+  fi
+}
+
+function _type_of() {
+  local _path="${1}"
+  local _content="${2}"
+  echo "${_content}" | jq -r -c "${_path}|type"
+}
+
+function _paths_type_of() {
+  local _type="${1}"
+  local _content="${2}"
+  local i
+  local -a _paths
+  debug "scanning _type=${_type},_content=${_content}"
+  mapfile -t _paths < <(all_paths "${_content}")
+  for i in "${_paths[@]}"; do
+    local _t
+    _t="$(_type_of "${i}" "${_content}")"
+    if [[ "${_t}" == "${_type}" ]]; then
+      debug "    read:'${i}'"
+      echo "${i}"
+    fi
+  done
+  debug "scanned"
+}
+
+function _perform_templating() {
+  local _content="${1}"
+  local _ret
+  local i
+  local -a _keys
+  debug "templating"
+  mapfile -t _keys < <(_paths_type_of "string" "${_content}")
+  debug "splitted"
+  for i in "${_keys[@]}"; do
+    local _node_value
+    local _templated_node_value
+    debug "processing:${i}"
+    _node_value="$(value_at "${i}" "${_content}")"
+    _templated_node_value="$(_render_text_node "${_node_value}" "${i}")"
+    if [[ -z "${_ret+empty}" ]]; then
+      debug "first node:'${i}':'${_templated_node_value}'"
+      _ret="$(jq -r -c -n "${i}=input" "$(mktemp_with_content "${_templated_node_value}")")"
+    else
+      local _a
+      local _b
+      debug "node:'${_ret}':'${i}':'${_templated_node_value}'"
+      _a=$(mktemp_with_content "${_ret}")
+      _b=$(mktemp_with_content "${_templated_node_value}")
+      _ret="$(jq -r -c -n "input|${i}=input" "${_a}" "${_b}")"
+    fi
+    debug "processed:${i}"
+  done
+  debug "templated:'${_ret}'"
+  echo "${_ret}"
 }
 
 function find_file_in_path() {
@@ -248,11 +353,11 @@ function expand_nodelevel_inheritances() {
   local _expanded_clean
   local _clean
   debug "begin:expand_nodelevel_inheritances:_target=${_target}"
-  debug "step(1):main:_target=${_target}"
+  debug "step(1):main:_target=${_target}: $?"
   _expanded=$(mktemp_with_content "$(_expand_nodelevel_inheritances "${_target}" "${_validation_mode}" "${_path}")")
-  debug "step(2a):remove meta nodes from target"
+  debug "step(2a):remove meta nodes from target: $?"
   _clean=$(mktemp_with_content "$(_remove_meta_nodes "${_target}")")
-  debug "step(2b):remove meta nodes from expanded"
+  debug "step(2b):remove meta nodes from expanded: $?"
   _expanded_clean=$(mktemp_with_content "$(_remove_meta_nodes "${_expanded}")")
   debug "step(3):merge object nodes"
   _merge_object_nodes "${_expanded_clean}" "${_clean}"
@@ -280,9 +385,7 @@ function perform_templating() {
   local _src_file="${1}"
   local _content
   local _ret
-  _content=$(sed -r 's/\"/\\\"/g' <"${_src_file}")
-  _ret=$(eval "echo \"${_content}\"") || quit "Failed to process a file '${_src_file}'(content='${_content}')"
-  echo "${_ret}"
+  _perform_templating "$(cat "${_src_file}")"
   debug "end:perform_templating"
 }
 
