Separate cur and curn functions and add descriptions for them in documentation

diff --git a/jq-front b/jq-front
--- a/jq-front
+++ b/jq-front
@@ -233,15 +233,22 @@ function _define_builtin_functions() {
     echo "${_self}"
   }
   ####
+  # A function that prints a node path to the text node, where the calls this function is directly made.
+  function curn() {
+    # shellcheck disable=SC2181
+    [[ $? == 0 ]] || abort "${_error_prefix}Failure was detected."
+    debug "cur:_path='${_path}'"
+    echo "${_path}"
+  }
+
+  ####
   # A function that prints a node path to a container element, which is an array or an object, that encloses the entry
   # belongs to.
   # An entry here means a pair of key and value or an element in an array.
   function cur() {
-    # shellcheck disable=SC2181
-    [[ $? == 0 ]] || abort "${_error_prefix}Failure was detected."
-    debug "cur:_path='${_path}'"
-    parent "${_path}"
+    parent "$(curn)"
   }
+
   ####
   # Prints a path to a parent node of a given path.
   # Note that single level path results in an empty string.
