Issue 65 user custom function support for templating (#66)
* Issue-#65: 
  ** User custom function support
  ** Improve performance
  ** Synchronize documentation

diff --git a/jq-front b/jq-front
--- a/jq-front
+++ b/jq-front
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-set -E -eu -o pipefail
+set -E -eu +o posix -o pipefail
 shopt -s inherit_errexit
 
 JF_BASEDIR=$(dirname "$(readlink --canonicalize "${0}")")
@@ -12,6 +12,10 @@ source "${JF_BASEDIR}/lib/shared.sh"
 function _debug_abort() {
   print_stacktrace "DEBUG: error trapped"
   exit 1
+}
+
+function _sourced_files_dir() {
+  echo "${_JF_SESSION_DIR}/source_files"
 }
 
 function _mangle_path() {
@@ -126,7 +130,7 @@ function _expand_nodelevel_inheritances() {
       else
         debug "_expand_nodelevel_inheritances: value NOT found at _p:'${_p}' in '${_cur_content}'"
         local _expanded_tmp
-        _expanded_tmp="$(run_jqfront ${_jj} "${_validation_mode}" "${_path}")"
+        _expanded_tmp="$(run_jqfront "${_jj}" "${_validation_mode}" "${_path}")"
         _merged_piece="$(mktemp_with_content "${_expanded_tmp}")"
       fi
       _tmp_content="$(jq -n "input | ${_p}=input" "${_cur}" "${_merged_piece}")"
@@ -164,10 +168,85 @@ function _validate_jf_json_with() {
   }
 }
 
+function _source_files() {
+  local _i _files
+  mapfile -t _files <<<"$(ls "$(_sourced_files_dir)")"
+  for _i in "${_files[@]}"; do
+    [[ "${_i}" == "" ]] && break
+    # shellcheck disable=SC1090
+    source "$(_sourced_files_dir)/${_i}"
+  done
+}
+
+function _define_builtin_functions() {
+  ####
+  #
+  # This is a function intended to be used on templating (_render_text_node)
+  function ref() {
+    # shellcheck disable=SC2181
+    [[ $? == 0 ]] || abort "${_error_prefix}Failure was detected."
+    local _path="${1}"
+    local value type
+    value=$(value_at "${_path}" "$(cat "$(self)")")
+    type="$(type_of "${value}")"
+    message "value:'${value}'"
+    message "type:'${type}'"
+    if [[ "${type}" == string && "${value}" == eval:* ]]; then
+      local ret
+      _check_cyclic_dependency "${_path}" reference
+      ret="$(_render_text_node "${value}" "${_path}" "${_self}")"
+      _unmark_as_in_progress "${_path}" reference
+      jq -r -c '.' <(echo "${ret}")
+    else
+      echo "${value}"
+    fi
+  }
+
+  ####
+  # Prints the entire file (before templating).
+  #
+  # This is a function intended to be used on templating (_render_text_node)
+  function self() {
+    # shellcheck disable=SC2181
+    [[ $? == 0 ]] || abort "${_error_prefix}Failure was detected."
+    echo "${_self}"
+  }
+  ####
+  # A function that prints a node path to an element that encloses the attribute.
+  function cur() {
+    # shellcheck disable=SC2181
+    [[ $? == 0 ]] || abort "${_error_prefix}Failure was detected."
+    echo "${_path%.*}"
+  }
+  ####
+  # Prints a path to a parent node of a given path.
+  # Note that single level path results in an empty string.
+  # That is ```parent .node``` will print nothing.
+  # This is intentional to be able to do ```$(ref $(parent $(cur)).uncle)``` even if ```$(cur)``` is either
+  # ```.node``` or ```.node.child```
+  function parent() {
+    # shellcheck disable=SC2181
+    [[ $? == 0 ]] || abort "${_error_prefix}Failure was detected."
+    local _p="${1?Path was not given}"
+    local _ret="${_p}"
+    if [[ ! "${_ret}" == .* ]]; then
+      abort "Path was not valid:(${_ret}), it must start with a '.'"
+    fi
+    if [[ "${_ret}" == "." ]]; then
+      abort "Root does not have a parent.:(${_ret})"
+    fi
+    _ret="${_ret%.*}"
+    echo "${_ret}"
+  }
+  function error() {
+    abort "${@}"
+  }
+}
+
 function _render_text_node() {
   local _node_value="${1}"
-  local _path="${2}"
-  local _self="${3}"
+  local _path="${2}" # DO NOT REMOVE: This local variable is referenced by built-in functions invoked on 'templating' stage.
+  local _self="${3}" # DO NOT REMOVE: This local variable is referenced by built-in functions invoked on 'templating' stage.
   local _mode="raw"
   local _quote="yes"
   local _body
@@ -190,71 +269,10 @@ function _render_text_node() {
 
   if [[ "${_mode}" == "template" || "${_mode}" == "eval" ]]; then
     local _error_prefix="ERROR: "
-    ####
-    #
-    # This is a function intended to be used on templating (_render_text_node)
-    function ref() {
-      # shellcheck disable=SC2181
-      [[ $? == 0 ]] || abort "${_error_prefix}Failure was detected."
-      local _path="${1}"
-      local value type
-      value=$(value_at "${_path}" "$(cat "$(self)")")
-      type="$(type_of "${value}")"
-      message "value:'${value}'"
-      message "type:'${type}'"
-      if [[ "${type}" == string && "${value}" == eval:* ]]; then
-        local ret
-        _check_cyclic_dependency "${_path}" reference
-        ret="$(_render_text_node "${value}" "${_path}" "${_self}")"
-        _unmark_as_in_progress "${_path}" reference
-        jq -r -c '.' <(echo "${ret}")
-      else
-        echo "${value}"
-      fi
-    }
-    ####
-    # Prints the entire file (before templating).
-    #
-    # This is a function intended to be used on templating (_render_text_node)
-    function self() {
-      # shellcheck disable=SC2181
-      [[ $? == 0 ]] || abort "${_error_prefix}Failure was detected."
-      echo "${_self}"
-    }
-    ####
-    # A function that prints a node path to an element that encloses the attribute.
-    function cur() {
-      # shellcheck disable=SC2181
-      [[ $? == 0 ]] || abort "${_error_prefix}Failure was detected."
-      echo "${_path%.*}"
-    }
-    ####
-    # Prints a path to a parent node of a given path.
-    # Note that single level path results in an empty string.
-    # That is ```parent .node``` will print nothing.
-    # This is intentional to be able to do ```$(ref $(parent $(cur)).uncle)``` even if ```$(cur)``` is either
-    # ```.node``` or ```.node.child```
-    function parent() {
-      # shellcheck disable=SC2181
-      [[ $? == 0 ]] || abort "${_error_prefix}Failure was detected."
-      local _p="${1?Path was not given}"
-      local _ret="${_p}"
-      if [[ ! "${_ret}" == .* ]]; then
-        abort "Path was not valid:(${_ret}), it must start with a '.'"
-      fi
-      if [[ "${_ret}" == "." ]]; then
-        abort "Root does not have a parent.:(${_ret})"
-      fi
-      _ret="${_ret%.*}"
-      echo "${_ret}"
-    }
-    function error() {
-      abort "${@}"
-    }
-    local _error
-    local _error_out
+    local _error _error_out
     export _path
     _error="$(mktemp)"
+    # Perform the 'templating'
     _ret="$(eval "echo \"${_body}\"" 2>"${_error}")"
     unset _path
     # shellcheck disable=SC2002
@@ -340,14 +358,22 @@ function find_file_in_path() {
       echo "${_file}"
     fi
   elif [[ ${#_arr[@]} -gt 1 ]]; then
-    ####
-    # In case the file name contains one or more semi-colons(';'), the name will be splitted by it.
-    # And a command line is constructed from them and executed.
     local _f
     _f="$(search_file_in "${_arr[0]}" "${_path}")" || abort "Script file ${_arr[1]} was not found in '${_path}'"
-    export _path
-    mktemp_with_content "$(${_arr[1]} "${_f}" "${_arr[@]:2}")"
-    unset _path
+    if [[ ${_arr[1]} == SOURCE ]]; then
+      # shellcheck disable=SC1090
+      #  We know that there are no non-alphanumerically named files.
+      # shellcheck disable=SC2012
+      cat "${_f}" >"$(_sourced_files_dir)/$(ls "$(_sourced_files_dir)" | wc -l)"
+      mktemp_with_content "{}"
+    else
+      ####
+      # In case the file name contains one or more semi-colons(';'), the name will be splitted by it.
+      # And a command line is constructed from them and executed.
+      export _path
+      mktemp_with_content "$(${_arr[1]} "${_f}" "${_arr[@]:2}")"
+      unset _path
+    fi
   fi
 }
 
@@ -451,8 +477,7 @@ function expand_filelevel_inheritances() {
   ####
   # This is intentionally using single quotes to pass quoted path expression to jq.
   # shellcheck disable=SC2016
-  local _cur
-  local _content
+  local _cur _content
   _in="$(find_file_in_path "${_target}" "${_path}")"
   debug "validating ${_in}"
   validate_jf_json "${_in}" "${_validation_mode}"
@@ -540,6 +565,10 @@ function perform_templating() {
   local _src_file="${1}"
   local _content
   local _ret
+  # define builtin functions such as "ref", "self"
+  _define_builtin_functions
+  # source files, for which SOURCE directive is specified
+  _source_files
   _perform_templating "$(cat "${_src_file}")"
   debug "end:perform_templating"
 }
@@ -552,6 +581,8 @@ function run_jqfront() {
   local _out
   debug "begin:run_jqfront:_target=${_target}"
   _target="$(find_file_in_path "${_target}" "${_jf_path}")"
+  # Fail on command substitution cannot be checked directly
+  # shellcheck disable=SC2181
   [[ $? == 0 ]] || abort "Failed to find a file '${_target}'."
   _jf_path="$(dirof "${_target}"):${_jf_path}"
   _content="$(cat "${_target}")"
@@ -588,6 +619,7 @@ function perform_jqfront() {
   local _validation_mode="${3}"
   local _jf_path="${4}"
   local _content
+  mkdir -p "$(_sourced_files_dir)"
   _content="$(run_jqfront "${_target}" "${_validation_mode}" "${_jf_path}")"
   _content=$(echo "${_content}" | jq '.|del(."$local")')
   if [[ "${_templating}" == "yes" ]]; then
