Issue-#83: Introduce Node Pool mechanism

diff --git a/jq-front b/jq-front
--- a/jq-front
+++ b/jq-front
@@ -131,19 +131,20 @@ function _expand_nodelevel_inheritances() {
       fi
       _check_cyclic_dependency "${j}" inheritance
       local _next_content
-      _next_content="$(read_file "${_jj}")"
+      _next_content="$(cat "${_jj}")"
       is_json "${_next_content}" || abort "Malformed JSON was given:'${_jj}'='${_next_content}'"
       _cur_content="$(cat "${_cur}")"
       local _merged_piece_content
       if has_value_at "${_p}" "${_cur_content}"; then
         local _cur_piece _next_piece
         _cur_piece="$(echo "${_cur_content}" | jq "${_p}")"
-        _next_piece="$(run_jqfront "${_jj}" "${_validation_mode}" "${_path}")"
+        _next_piece="$(expand_inheritances "${_jj}" "${_validation_mode}" "${_path}")"
         _merged_piece_content="$(_merge_object_nodes "${_cur_piece}" "${_next_piece}")"
         [[ $? == 0 ]] || abort "Failed to merge file:'${_cur}' with file:'${_jj}'"
       else
         local _expanded_tmp
-        _expanded_tmp="$(run_jqfront "${_jj}" "${_validation_mode}" "${_path}")" || abort "TODO(0)"
+        _expanded_tmp="$(expand_inheritances "${_jj}" "${_validation_mode}" "${_path}")" ||
+          abort "Failed to expand inheritances for '${_jj}'"
         _merged_piece_content="${_expanded_tmp}"
       fi
       _tmp_content="$(jq -n "input | ${_p}=input" "${_cur}" <(echo "${_merged_piece_content}"))"
@@ -200,7 +201,7 @@ function _define_builtin_functions() {
     [[ $? == 0 ]] || abort "${_error_prefix}Failure was detected."
     local _path="${1}"
     local value type
-    value=$(value_at "${_path}" "$(read_file "$(self)")")
+    value=$(value_at "${_path}" "$(cat "$(self)")")
     type="$(type_of "${value}")"
     debug "value:'${value}'(type:'${type}')"
     if [[ "${type}" == string && ("${value}" == eval:* || "${value}" == template:*) ]]; then
@@ -384,7 +385,7 @@ function find_file_in_path() {
       # shellcheck disable=SC1090
       #  We know that there are no non-alphanumerically named files.
       # shellcheck disable=SC2012
-      read_file "${_f}" >"$(_sourced_files_dir)/$(ls "$(_sourced_files_dir)" | wc -l)"
+      cat "${_f}" >"$(_sourced_files_dir)/$(ls "$(_sourced_files_dir)" | wc -l)"
       mktemp_with_content "{}"
     else
       ####
@@ -503,7 +504,7 @@ function expand_filelevel_inheritances() {
   validate_jf_json "${_in}" "${_validation_mode}"
   debug "...validated"
   _check_cyclic_dependency "${_in}" inheritance
-  _content="$(read_file "${_in}")"
+  _content="$(cat "${_in}")"
   _cur="${_content}"
   if is_object "${_content}"; then
     # shellcheck disable=SC2016
@@ -512,7 +513,7 @@ function expand_filelevel_inheritances() {
       local i
       while IFS= read -r i; do
         local _next _c _parent
-        _parent="$(run_jqfront "${i}" "${_validation_mode}" "${_path}")"
+        _parent="$(expand_inheritances "${i}" "${_validation_mode}" "${_path}")"
         _c="$(_merge_object_nodes "${_parent}" "${_cur}")"
         # Cannot check the exit code directly because of command substitution
         # shellcheck disable=SC2181
@@ -524,7 +525,7 @@ function expand_filelevel_inheritances() {
     _cur_tmpfile="$(mktemp_with_content "${_cur}")"
     jq -r -c '.|del(.["$extends"])' "${_cur_tmpfile}"
   else
-    read_file "$(find_file_in_path "${_cur}" "${_path}")"
+    cat "$(find_file_in_path "${_cur}" "${_path}")"
   fi
   _unmark_as_in_progress "${_in}" inheritance
   perf "end"
@@ -534,7 +535,7 @@ function materialize_private_nodes() {
   local _target="${1}"
   local _content _ret
   debug "begin:materialize_private_nodes"
-  _content="$(read_file "${_target}")"
+  _content="$(cat "${_target}")"
   _ret="$(mktemp -d)"
   # Intentional single quotes for jq.
   # shellcheck disable=SC2016
@@ -554,7 +555,7 @@ function expand_nodelevel_inheritances() {
   local _path="${3}"
   local _expanded _expanded_clean _clean _content _ret
   perf "begin:_target=${_target}"
-  _content="$(read_file "${_target}")"
+  _content="$(cat "${_target}")"
   _expanded="$(_expand_nodelevel_inheritances "${_content}" "${_validation_mode}" "${_path}")" ||
     abort "Failed to expand node level inheritance for file:'${_target}'(1)"
   _clean="$(_remove_meta_nodes "${_content}")"
@@ -573,37 +574,44 @@ function expand_inheritances_of_private_nodes() {
     local _tmp
     local _f="${i}"
     debug "expanding inheritance of private node:${i}"
-    _tmp="$(mktemp_with_content "$(run_jqfront "${_f}" "no" "${_path}:${_jf_path}")")"
+    _tmp="$(mktemp_with_content "$(expand_inheritances "${_f}" "no" "${_path}:${_jf_path}")")"
     cp "${_tmp}" "${_f}"
     debug "...expanded"
   done < <(find "${_path}" -maxdepth 1 -type f -print0)
   debug "end:   expand_inheritances_of_private_nodes"
 }
 
-function perform_templating() {
-  perf "begin"
-  local _src_file="${1}"
-  local _content _ret
-  # define builtin functions such as "ref", "self"
-  _define_builtin_functions
-  # source files, for which SOURCE directive is specified
-  _source_files
-  _perform_templating "$(cat "${_src_file}")"
-  perf "end"
+function prepare_pooldir() {
+  mktemp -d
 }
 
-function run_jqfront() {
+function expand_inheritances() {
+  local _filename="${1}"
+  local _validation_mode="${2}"
+  local _jf_path="${3}"
+  local _caching_filename
+  _caching_filename="${_JF_POOL_DIR}/$(echo -n "${_filename}" | md5sum | cut -f 1 -d ' ')"
+  perf "begin: ${_filename}"
+  [[ -e "${_caching_filename}" ]] || {
+    perf "expanding inheritances for file: '${_filename}'"
+    _expand_inheritances "${_filename}" "${_validation_mode}" "${_jf_path}" >"${_caching_filename}"
+  }
+  cat "${_caching_filename}"
+  perf "end: ${_filename} (cached in ${_caching_filename})"
+}
+
+function _expand_inheritances() {
   local _target="${1}"
   local _validation_mode="${2}"
   local _jf_path="${3}"
   local _content _out
-  perf "begin"
+  perf "begin: ${_target}"
   _target="$(find_file_in_path "${_target}" "${_jf_path}")"
   # Fail on command substitution cannot be checked directly
   # shellcheck disable=SC2181
   [[ $? == 0 ]] || abort "Failed to find a file '${_target}'."
   _jf_path="$(dirof "${_target}"):${_jf_path}"
-  _content="$(read_file "${_target}")"
+  _content="$(cat "${_target}")"
   if ! is_json "${_content}"; then
     abort "Malformed JSON was given:'${_target}'='${_content}'"
   fi
@@ -626,6 +634,18 @@ function run_jqfront() {
     _out="$(mktemp_with_content "${_content}")"
   fi
   cat "${_out}"
+  perf "end: ${_target}"
+}
+
+function perform_templating() {
+  perf "begin"
+  local _src_file="${1}"
+  local _content _ret
+  # define builtin functions such as "ref", "self"
+  _define_builtin_functions
+  # source files, for which SOURCE directive is specified
+  _source_files
+  _perform_templating "$(cat "${_src_file}")"
   perf "end"
 }
 
@@ -637,7 +657,7 @@ function perform_jqfront() {
   local _content
   perf "begin"
   mkdir -p "$(_sourced_files_dir)"
-  _content="$(run_jqfront "${_target}" "${_validation_mode}" "${_jf_path}")"
+  _content="$(expand_inheritances "${_target}" "${_validation_mode}" "${_jf_path}")"
   _content=$(echo "${_content}" | jq '.|del(."$local")')
   if [[ "${_templating}" == "yes" ]]; then
     local _out
@@ -730,5 +750,7 @@ if [[ -n "${_JF_PATH_BASE}" ]]; then
   export TMPDIR="${_JF_PATH_BASE}/tmp"
 fi
 export_names_for_script_inheritance
+export _JF_POOL_DIR
+_JF_POOL_DIR="$(prepare_pooldir)"
 
 main "${@}"
