Fix a few bugs in templating improvement

diff --git a/jq-front b/jq-front
--- a/jq-front
+++ b/jq-front
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-set -eu
+set -Eeu
 
 JF_BASEDIR=$(dirname "$(readlink --canonicalize "${0}")")
 export JF_BASEDIR
@@ -15,11 +15,16 @@ function _mangle_path() {
   local _path="${1}"
   local _path_base="${2}"
   local _ret=""
+  if [[ -z "${_path_base}" ]]; then
+    echo "${_path}"
+    return 0
+  fi
   IFS=":" read -r -a _arr <<<"${_path}"
   for i in "${_arr[@]}"; do
     local _cur="${_path_base}"
     if [[ ${i} == .* ]]; then
-      _cur="${_cur}/${i/./${_JF_CWD}}"
+      # _JF_CWD always starts with '/' since it is an absolute path to current working directory by definition.
+      _cur="${_cur}${i/./${_JF_CWD}}"
     else
       _cur="${_cur}${i}"
     fi
@@ -29,7 +34,7 @@ function _mangle_path() {
       _ret="${_ret}:${_cur}"
     fi
   done
-  echo ":${_JF_PATH_BASE}:${_ret}"
+  echo "${_path_base}:${_ret}"
 }
 
 function _remove_meta_nodes() {
@@ -39,14 +44,16 @@ function _remove_meta_nodes() {
   _content="$(cat "${_target}")"
   if [[ $(is_object "${_content}") == true ]]; then
     _cur="$(mktemp_with_content "$(cat "${_target}")")"
+    local _keys
+    IFS=$'\n' read -d '' -r -a _keys <<<"$(all_paths "${_content}" | grep '"$extends"$')"
     # Intentional single quote to find a keyword that starts with '$'
     # shellcheck disable=SC2016
-    for i in $(all_paths "${_content}" | grep '"$extends"$'); do
+    for i in "${_keys[@]}"; do
       local _next
       _next="$(mktemp_with_content "$(jq ".|del(${i})" "${_cur}")")"
       _cur="${_next}"
     done
-    jq '.|del(."$private")' "${_cur}"
+    cat "${_cur}"
   else
     echo "${_content}"
   fi
@@ -56,45 +63,59 @@ function _remove_meta_nodes() {
 function _merge_object_nodes() {
   local _a="${1}"
   local _b="${2}"
-  jq -s '.[0] * .[1]' "${_a}" "${_b}"
+  jq -s '.[0] * .[1]' "${_a}" "${_b}" || {
+    abort "Failed to merge object nodes:'${_a}' and '${_b}'"
+  }
 }
 
-function _expand_internal_inheritances() {
+function _expand_nodelevel_inheritances() {
   local _target="${1}"
   local _validation_mode="${2}"
-  local _private_nodes_dir="${3}"
+  local _path="${3}"
   local _cur
   local _in
+  local _keys
   _cur=$(mktemp_with_content '{}')
-  debug "(begin:_expand_internal_inheritances:1)"
+  debug "(begin:_expand_nodelevel_inheritances:1:${_target})"
   # Intentional single quote to find a keyword that starts with '$'
   # shellcheck disable=SC2016
-  for i in $(all_paths "$(cat "${_target}")" | grep '"$extends"$'); do
-    debug "->_expand_internal_inheritances:2:${i})"
-    while IFS= read -r j; do
+  IFS=$'\n' read -d '' -r -a _keys <<<"$(all_paths "$(cat "${_target}")" | grep '"$extends"$')"
+  for i in "${_keys[@]}"; do
+    debug "->_expand_nodelevel_inheritances:2:i='${i}')"
+    local -a _extendeds
+    IFS=$'\n' read -d '' -r -a _extendeds <<<"$(jq -r -c "${i}[]" "${_target}")"
+    for j in "${_extendeds[@]}"; do
       local _next
       local _jj
-      debug "-->_expand_internal_inheritances:3:${j})"
-      _jj="$(read_file_from_path "${j}" "${_private_nodes_dir}")"
-      validate_jf_json "${_jj}" "${_validation_mode}" || abort "failed on validation"
       local _merged_piece
       local _p
-      _p="${i%.\"\$extends\"}"
       local _cur_content
+      local _tmp_content
+      debug "-->_expand_nodelevel_inheritances:3:j='${j}')"
+      _jj="$(find_file_in_path "${j}" "${_path}")"
+      debug "-->_expand_nodelevel_inheritances:4:resolved '${j}'->'${_jj}'"
+      validate_jf_json "${_jj}" "${_validation_mode}" || abort "failed on validation"
+      debug "-->_expand_nodelevel_inheritances:5:validated '${_jj}'"
+      _p="${i%.\"\$extends\"}"
       _cur_content="$(cat "${_cur}")"
+      debug "-->_expand_nodelevel_inheritances:6:merging nodes at '${_p}'"
       if [[ $(has_value_at "${_p}" "${_cur_content}") == true ]]; then
         local _cur_piece
         _cur_piece=$(mktemp_with_content "$(echo "${_cur_content}" | jq "${_p}")")
         _merged_piece=$(mktemp_with_content "$(_merge_object_nodes "${_cur_piece}" "${_jj}")")
       else
-        _merged_piece=${_jj}
+        _merged_piece="${_jj}"
       fi
-      _next=$(mktemp_with_content "$(jq -n "input | ${_p}=input" "${_cur}" "${_merged_piece}")") ||
-        abort "failed on node replacing; _cur=$(cat "${_cur}"); _merged_piece=$(cat "${_merged_piece}")"
+      debug "-->_expand_nodelevel_inheritances:7:merged"
+      _tmp_content="$(jq -n "input | ${_p}=input" "${_cur}" "${_merged_piece}")"
+      [[ $? == 0 ]] || abort "Failed to merge nodes:_p=${_p},_merged_piece=${_merged_piece}"
+      debug "-->_expand_nodelevel_inheritances:8:written:$?"
+      _next=$(mktemp_with_content "${_tmp_content}")
       _cur="${_next}"
-    done <<<"$(jq -r -c "${i}[]" "${_target}")"
+      debug "-->_expand_nodelevel_inheritances:9:trying:i=${i} on _target=${_target}"
+    done
   done
-  debug "(end:_expand_internal_inheritances:1)"
+  debug "(end:_expand_nodelevel_inheritances:1)"
   jq -r -c . "${_cur}"
 }
 
@@ -104,10 +125,100 @@ function _validate_jf_json_with() {
   local _out=
   {
     _out=$(ajv validate -s "${_JF_SCHEMA_DIR}/${_mode}.json" -d "${_in}" 2>&1)
-  } || abort "Validation for '${_in}' was failed:\n${_out}"
+  } || {
+    quit "Validation by ajv for '${_in}' was failed:\n${_out}"
+  }
 }
 
-function read_file_from_path() {
+function _render_text_node() {
+  local _node_value="${1}"
+  local _path="${2}"
+  local _mode="raw"
+  local _quote="yes"
+  local _body
+  local _ret
+  debug "rendering"
+  if [[ "${_node_value}" == template:* || "${_node_value}" == raw:* ]]; then
+    _mode="${_node_value%%:*}"
+    _body="${_node_value#*:}"
+    if [[ "${_body}" == object:* || "${_body}" == array:* ||
+    "${_body}" == string:* || "${_body}" == number:* || "${_body}" == boolean:* ]] \
+      ; then
+      if [[ "${_body}" != string:* ]]; then
+        _quote="no"
+      fi
+      _body="${_body#*:}"
+    fi
+  else
+    _body="${_node_value}"
+  fi
+
+  if [[ "${_mode}" == "template" ]]; then
+    _ret=$(eval echo "${_body}")
+  elif [[ "${_mode}" == "raw" ]]; then
+    _ret="${_body}"
+  fi
+  debug "rendered:_mode='${_mode}'"
+  if [[ "${_quote}" == yes ]]; then
+    _ret="${_ret//\\/\\\\}"
+    echo "\"${_ret//\"/\\\"}\""
+  else
+    echo "${_ret}"
+  fi
+}
+
+function _type_of() {
+  local _path="${1}"
+  local _content="${2}"
+  echo "${_content}" | jq -r -c "${_path}|type"
+}
+
+function _paths_type_of() {
+  local _type="${1}"
+  local _content="${2}"
+  local i
+  local -a _paths
+  debug "scanning _type=${_type},_content=${_content}"
+  mapfile -t _paths < <(all_paths "${_content}")
+  for i in "${_paths[@]}"; do
+    local _t
+    _t="$(_type_of "${i}" "${_content}")"
+    if [[ "${_t}" == "${_type}" ]]; then
+      debug "    read:'${i}'"
+      echo "${i}"
+    fi
+  done
+  debug "scanned"
+}
+
+function _perform_templating() {
+  local _content="${1}"
+  local _ret="${_content}"
+  local i
+  local -a _keys
+  debug "templating"
+  mapfile -t _keys < <(_paths_type_of "string" "${_content}")
+  debug "splitted"
+  for i in "${_keys[@]}"; do
+    local _node_value
+    local _templated_node_value
+    debug "processing:${i}"
+    _node_value="$(value_at "${i}" "${_content}")"
+    _templated_node_value="$(_render_text_node "${_node_value}" "${i}")"
+    local _a
+    local _b
+    debug "node:'${_ret}':'${i}':'${_templated_node_value}'"
+    _a=$(mktemp_with_content "${_ret}")
+    _b=$(mktemp_with_content "${_templated_node_value}")
+    _ret="$(jq -r -c -n "input|${i}=input" "${_a}" "${_b}")"
+    [[ $? == 0 ]] || abort "Failed to replace node at '${i}' with '$(cat ${_b})'"
+    debug "processed:${i}"
+  done
+  debug "templated:'${_ret}'"
+  echo "${_ret}"
+}
+
+function find_file_in_path() {
   local _target="${1}"
   local _path="${2}"
   IFS=';' read -r -a _arr <<<"${_target}"
@@ -115,18 +226,38 @@ function read_file_from_path() {
     search_file_in "${1}" "${2}"
     return $?
   elif [[ ${#_arr[@]} -gt 1 ]]; then
+    ####
+    # In case the file name contains one or more semi-colons(';'), the name will be splitted by it.
+    # And a command line is constructed from them and executed.
     local _f
     _f="$(search_file_in "${_arr[0]}" "${_path}")" || quit "Script file ${_arr[1]} was not found in '${_path}'"
+    export _path
     mktemp_with_content "$(${_arr[1]} "${_f}" "${_arr[@]:2}")"
+    unset _path
     return $?
   fi
 }
 
+####
+#
+# Function intended to be used on 'script inheritance'.
+# Search for a file from an environment variable "_JF_PATH" and prints an absolute path of it if found.
+# In case it is not found, 1 will be returned.
+#
+# This function is indirectly called by 'find_file_in_path' through a command line it constructs
+#
+function find_file() {
+  local _target="${1}"
+  search_file_in "${_target}" "${_path}"
+}
+
 function export_names_for_script_inheritance() {
-    export -f find_file
-    export -f search_file_in
-    export _JF_PATH
-    export _JF_PATH_BASE
+  export -f find_file
+  export -f search_file_in
+  export -f quit
+  export -f message
+  export _JF_PATH
+  export _JF_PATH_BASE
 }
 
 function validate_jf_json() {
@@ -135,29 +266,40 @@ function validate_jf_json() {
   if [[ "${_mode}" == "no" ]]; then
     return 0
   elif [[ "${_mode}" == "strict" ]]; then
-    _validate_jf_json_with "${_in}" "strict" || return 1
+    _validate_jf_json_with "${_in}" "strict"
   elif [[ "${_mode}" == "lenient" ]]; then
-    _validate_jf_json_with "${_in}" "lenient" || return 1
+    _validate_jf_json_with "${_in}" "lenient"
   else
-    message "Unknown validation mode:'${_mode}' was set."
-    exit 1
+    abort "Unknown validation mode:'${_mode}' was set."
   fi
+  return $?
 }
 
-function expand_external_inheritances() {
+function dirof() {
+  local _target="${1}"
+  local _ret
+  _ret=$(dirname "$(readlink --canonicalize-missing "${_target}")")
+  echo "${_ret}"
+}
+
+function expand_filelevel_inheritances() {
   local _target="${1}"
   local _validation_mode="${2}"
   local _path="${3}"
   local _in
-  debug "begin:expand_external_inheritances:target=${_target}"
+  debug "begin:expand_filelevel_inheritances:_target=${_target}"
   ####
   # This is intentionally using single quotes to pass quoted path expression to jq.
   # shellcheck disable=SC2016
   local _cur
   local _content
-  _in="$(read_file_from_path "${_target}" "${_path}")" || quit "${_target} was not found in ${_path}"
+  _in="$(find_file_in_path "${_target}" "${_path}")"
   debug "validating ${_in}"
-  validate_jf_json "${_in}" "${_validation_mode}" || quit "Validation failed:${_in}:content=""$(cat "${_in}")"""
+  validate_jf_json "${_in}" "${_validation_mode}"
+  ####
+  # Strangely the line above does not causes a quit on a failure.
+  # Explitly check and abotrt this functino.
+  [[ $? == 0 ]] || abort "Failed to process '${_target}'"
   debug "...validated"
   _content="$(cat "${_in}")"
   _cur="$(mktemp_with_content "${_content}")"
@@ -169,16 +311,16 @@ function expand_external_inheritances() {
       while IFS= read -r i; do
         local _next
         local _tmp
-        _tmp=$(mktemp_with_content "$(expand_external_inheritances "$i" "${_validation_mode}" "${_path}")")
+        _tmp=$(mktemp_with_content "$(run_jqfront "${i}" "${_validation_mode}" "${_path}")")
         _next=$(mktemp_with_content "$(_merge_object_nodes "${_tmp}" "${_cur}")")
         _cur="${_next}"
       done <<<"$(value_at '."$extends"[]' "${_content}")"
     fi
-    jq -r -c '.|del(.["$extends"])' "$(read_file_from_path "${_cur}" "${_path}")"
+    jq -r -c '.|del(.["$extends"])' "$(find_file_in_path "${_cur}" "${_path}")"
   else
-    cat "$(read_file_from_path "${_cur}" "${_path}")"
+    cat "$(find_file_in_path "${_cur}" "${_path}")"
   fi
-  debug "end:expand_external_inheritances"
+  debug "end:expand_filelevel_inheritances"
 }
 
 function materialize_private_nodes() {
@@ -190,48 +332,48 @@ function materialize_private_nodes() {
   _ret="$(mktemp -d)"
   # Intentional single quotes for jq.
   # shellcheck disable=SC2016
-  if [[ $(has_value_at '."$private"' "${_content}") == true ]]; then
+  if [[ $(has_value_at '."$local"' "${_content}") == true ]]; then
     # shellcheck disable=SC2016
-    for i in $(keys_of '."$private"' "${_content}"); do
-      echo "${_content}" | jq '."$private".''"'"${i}"'"' >"${_ret}/${i}"
+    for i in $(keys_of '."$local"' "${_content}"); do
+      echo "${_content}" | jq '."$local".''"'"${i}"'"' >"${_ret}/${i}"
     done
   fi
   echo "${_ret}"
   debug "end:materialize_private_nodes"
 }
 
-function expand_internal_inheritances() {
+function expand_nodelevel_inheritances() {
   local _target="${1}"
   local _validation_mode="${2}"
-  local _private_nodes_dir="${3}"
+  local _path="${3}"
   local _expanded
   local _expanded_clean
   local _clean
-  debug "begin:expand_internal_inheritances"
-  debug "step(1):main"
-  _expanded=$(mktemp_with_content "$(_expand_internal_inheritances "${_target}" "${_validation_mode}" "${_private_nodes_dir}")")
-  debug "step(2a):remove meta nodes from target"
+  debug "begin:expand_nodelevel_inheritances:_target=${_target}"
+  debug "step(1):main:_target=${_target}: $?"
+  _expanded=$(mktemp_with_content "$(_expand_nodelevel_inheritances "${_target}" "${_validation_mode}" "${_path}")")
+  debug "step(2a):remove meta nodes from target: $?"
   _clean=$(mktemp_with_content "$(_remove_meta_nodes "${_target}")")
-  debug "step(2b):remove meta nodes from expanded"
+  debug "step(2b):remove meta nodes from expanded: $?"
   _expanded_clean=$(mktemp_with_content "$(_remove_meta_nodes "${_expanded}")")
   debug "step(3):merge object nodes"
   _merge_object_nodes "${_expanded_clean}" "${_clean}"
-  debug "end:expand_internal_inheritances"
+  debug "end:expand_nodelevel_inheritances"
 }
 
 function expand_inheritances_of_private_nodes() {
-  local _private_nodes_dir="${1}"
+  local _path="${1}"
   local _templating="${2}"
   local _jf_path="${3}"
-  debug "begin: expand_inheritances_of_private_nodes in ${_private_nodes_dir}"
+  debug "begin: expand_inheritances_of_private_nodes in ${_path}"
   while IFS= read -r -d '' i; do
     local _tmp
     local _f="${i}"
     debug "expanding inheritance of private node:${i}"
-    _tmp="$(mktemp_with_content "$(run_jf "${_f}" "no" "no" "${_private_nodes_dir}:${_jf_path}")")"
+    _tmp="$(mktemp_with_content "$(run_jqfront "${_f}" "no" "${_path}:${_jf_path}")")"
     cp "${_tmp}" "${_f}"
     debug "...expanded"
-  done < <(find "${_private_nodes_dir}" -maxdepth 1 -type f -print0)
+  done < <(find "${_path}" -maxdepth 1 -type f -print0)
   debug "end:   expand_inheritances_of_private_nodes"
 }
 
@@ -240,60 +382,57 @@ function perform_templating() {
   local _src_file="${1}"
   local _content
   local _ret
-  _content=$(sed -r 's/\"/\\\"/g' <"${_src_file}")
-  _ret=$(eval "echo \"${_content}\"") || {
-      message "Failed to process a file '${_src_file}'(content='${_content}')"
-      return 1
-    }
-  echo "${_ret}"
+  _perform_templating "$(cat "${_src_file}")"
   debug "end:perform_templating"
 }
 
-####
-#
-# Function intended to be used on 'script inheritance'.
-# Search for a file from an environment variable "_JF_PATH" and prints an absolute path of it if found.
-# In case it is not found, 1 will be returned
-#
-function find_file() {
+function run_jqfront() {
   local _target="${1}"
-  search_file_in "${_target}" "${_JF_PATH}" || {
-    return $?
-  }
-  return 0
-}
-
-function run_jf() {
-  local _target="${1}"
+  local _validation_mode="${2}"
+  local _jf_path="${3}"
   local _content
-  local _templating="${2}"
-  local _jf_path="${4}"
   local _out
-  debug "begin:run_jf"
-  _target="$(read_file_from_path "${_target}" "${_jf_path}")"
+  debug "begin:run_jf:_target=${_target}"
+  _target="$(find_file_in_path "${_target}" "${_jf_path}")"
+  _jf_path="$(dirof "${_target}"):${_jf_path}"
   _content="$(cat "${_target}")" || abort "Failed to read file '${_target}'"
   if [[ $(is_object "${_content}") == true ]]; then
     local _tmp
-    local _validation_mode="${3}"
     local _private_nodes_dir
-    # If we use mktemp_with_content here, somehow an error happens. Let's fix it later.
-    _tmp="$(mktemp)"
-    expand_external_inheritances "${_target}" "${_validation_mode}" "${_jf_path}" >"${_tmp}"
+    local _c
+    _c="$(expand_filelevel_inheritances "${_target}" "${_validation_mode}" "${_jf_path}")"
+    ####
+    # Strangely the line above does not causes a quit on a failure.
+    # Explitly check and abotrt this functino.
+    [[ $? == 0 ]] || abort "File-level expansion failed for '${_target}'"
+    _tmp="$(mktemp_with_content "${_c}")"
     _private_nodes_dir=$(materialize_private_nodes "${_tmp}")
     expand_inheritances_of_private_nodes "${_private_nodes_dir}" \
       "${_templating}" \
       "${_private_nodes_dir}:${_jf_path}"
-    _out=$(mktemp_with_content "$(expand_internal_inheritances "${_tmp}" "${_validation_mode}" "${_private_nodes_dir}:${_jf_path}")")
+    _out=$(mktemp_with_content "$(expand_nodelevel_inheritances "${_tmp}" "${_validation_mode}" "${_private_nodes_dir}:${_jf_path}")")
   else
     debug "non object file:${_target}"
     _out="$(mktemp_with_content "${_content}")"
   fi
-  if [[ "${_templating}" == "yes" ]]; then
-    perform_templating "${_out}"
-  else
-    cat "${_out}"
-  fi
+  cat "${_out}"
   debug "end:run_jf"
+}
+
+function perform_jqfront() {
+  local _target="${1}"
+  local _templating="${2}"
+  local _validation_mode="${3}"
+  local _jf_path="${4}"
+  local _content
+  _content="$(run_jqfront "${_target}" "${_validation_mode}" "${_jf_path}")"
+  _content=$(echo "${_content}" | jq '.|del(."$local")')
+  if [[ "${_templating}" == "yes" ]]; then
+    local _out
+    _out=$(mktemp_with_content "${_content}")
+    _content=$(perform_templating "${_out}")
+  fi
+  echo "${_content}"
 }
 
 function usage_exit() {
@@ -340,7 +479,7 @@ function main() {
   else
     _target="${1}"
   fi
-  run_jf "${_target}" "${_JF_TEMPLATING_ENABLED}" "${_JF_VALIDATION}" "${_JF_PATH}"
+  perform_jqfront "${_target}" "${_JF_TEMPLATING_ENABLED}" "${_JF_VALIDATION}" "${_JF_PATH}"
 }
 
 _JF_CWD="${JF_CWD:-"$(pwd)"}"
@@ -354,12 +493,19 @@ _JF_DEBUG=${JF_DEBUG:-"disabled"}
 
 debug "_JF_CWD=${_JF_CWD}"
 debug "_JF_BASEDIR=${_JF_BASEDIR}"
+####
+# JF_PATH_BASE is set when this program is run under Docker.
 debug "_JF_PATH_BASE=${_JF_PATH_BASE}"
 debug "_JF_PATH=${_JF_PATH}"
 debug "_JF_TEMPLATING_ENABLED=${_JF_TEMPLATING_ENABLED}"
 debug "_JF_VALIDATION=${_JF_VALIDATION}"
 debug "_JF_DEBUG=${_JF_DEBUG}"
 
+####
+# Export JF_PATH_BASE, which is set for executions under Docker
+if [[ -n "${_JF_PATH_BASE}" ]]; then
+  export TMPDIR="${_JF_PATH_BASE}/tmp"
+fi
 export_names_for_script_inheritance
 
 main "${@}"
