Correct a logic to build a string passed to jq-front through xargs

diff --git a/jq-front b/jq-front
--- a/jq-front
+++ b/jq-front
@@ -79,6 +79,7 @@ function main() {
   local options
   local xargs_options="" xargs="no" xargs_jqfront_options=("${@}")
   local outfile=""
+  info "command line: ${0} ${*}"
   # Call getopt to validate the provided input.
   options=$(getopt \
     -o heo: \
@@ -131,25 +132,30 @@ function main() {
     done
   fi
   if [[ "${xargs}" == "yes" ]]; then
-    local i
+    local i _cmd
     for i in "${!xargs_jqfront_options[@]}"; do
       [[ "${xargs_jqfront_options[${i}]}" == "--xargs="* ]] && unset -v 'xargs_jqfront_options[$i]'
     done
     xargs_jqfront_options=("${xargs_jqfront_options[@]}")
-    # shellcheck disable=SC2086
-    debug "command line: '"xargs ${xargs_options} "$(readlink -f ${BASH_SOURCE[0]})" "${xargs_jqfront_options[@]}" "'"
-    xargs ${xargs_options} bash -c "$(readlink -f "${BASH_SOURCE[0]}")" "${xargs_jqfront_options[@]}"
+    _cmd="$(readlink -f "${BASH_SOURCE[0]}") ${xargs_jqfront_options[*]}"
+    info "batch-mode: command line: 'xargs ${xargs_options} bash -c \"${_cmd}\"'"
+    xargs ${xargs_options} bash -c "${_cmd}"
   else
     function perform() {
-      perform_jqfront "${_target}" "${_JF_TEMPLATING_ENABLED}" "${_JF_NESTED_TEMPLATING_LEVELS}" "${_JF_VALIDATION}" "${_JF_PATH}" ${outfile}
+      perform_jqfront "${_target}" "${_JF_TEMPLATING_ENABLED}" "${_JF_NESTED_TEMPLATING_LEVELS}" "${_JF_VALIDATION}" "${_JF_PATH}"
     }
     if [[ $# == 0 ]]; then
-      _target="$(mktemp_with_content "$(cat)")"
+      _target="$(mktemp_with_content "$(cat)")" || abort "Failed to create a temporary file"
     else
       _target="${1}"
     fi
     mkdir -p "${_JF_SESSION_DIR}"
     if [[ "${outfile}" != "" ]]; then
+      local _dir
+      _dir="$(dirname "${outfile}")"
+      [[ -d "${_dir}" ]] || abort "No directory:'${_dir}' is found"
+      [[ -w "${_dir}" ]] || abort "Cannot write a file under a directory:'${_dir}'"
+      [[ ! -e "${outfile}" || -w "${outfile}" ]] || abort "Cannot write to a file:'${outfile}'"
       perform >"${outfile}"
     else
       perform
@@ -164,6 +170,7 @@ _JF_PATH=$(_mangle_path "${JF_PATH:-"."}" "${_JF_PATH_BASE}")
 _JF_TEMPLATING_ENABLED=${JF_TEMPLATING_ENABLED:-"yes"}
 _JF_NESTED_TEMPLATING_LEVELS=5
 _JF_VALIDATION=${JF_VALIDATION:-"no"}
+_JF_INFO=${JF_INFO:-"disabled"}
 _JF_DEBUG=${JF_DEBUG:-"disabled"}
 _JF_PERF=${JF_PERF:-"${_JF_DEBUG}"}
 _JF_SESSION_ID="$(date +%s.%N)"
@@ -178,6 +185,7 @@ debug "_JF_PATH=${_JF_PATH}"
 debug "_JF_TEMPLATING_ENABLED=${_JF_TEMPLATING_ENABLED}"
 debug "_JF_NESTED_TEMPLATING_LEVELS=${_JF_NESTED_TEMPLATING_LEVELS}"
 debug "_JF_VALIDATION=${_JF_VALIDATION}"
+debug "_JF_INFO=${_JF_INFO}"
 debug "_JF_DEBUG=${_JF_DEBUG}"
 debug "_JF_PERF=${_JF_PERF}"
 
