Separate functions into files

diff --git a/jq-front b/jq-front
--- a/jq-front
+++ b/jq-front
@@ -11,56 +11,15 @@ source "${JF_BASEDIR}/lib/shared.sh"
 # shellcheck disable=SC1090
 # source = lib/nodepool.sh
 source "${JF_BASEDIR}/lib/nodepool.sh"
-
-function _debug_abort() {
-  print_stacktrace "DEBUG: error trapped"
-  exit 1
-}
-
-function _mangle_path() {
-  local _path="${1}" _path_base="${2}"
-  local _ret=""
-  if [[ -z "${_path_base}" ]]; then
-    echo "${_path}"
-    return 0
-  fi
-  IFS=":" read -r -a _arr <<<"${_path}"
-  for i in "${_arr[@]}"; do
-    local _cur="${_path_base}"
-    if [[ ${i} == .* ]]; then
-      # _JF_CWD always starts with '/' since it is an absolute path to current working directory by definition.
-      _cur="${_cur}${i/./${_JF_CWD}}"
-    else
-      _cur="${_cur}${i}"
-    fi
-    if [[ "${_ret}" == "" ]]; then
-      _ret="${_cur}"
-    else
-      _ret="${_ret}:${_cur}"
-    fi
-  done
-  echo "${_path_base}:${_ret}"
-}
-
-function _remove_meta_nodes() {
-  local _content="${1}"
-  local _cur
-  if is_object "${_content}"; then
-    local _keys i
-    _cur="$(mktemp_with_content "${_content}")"
-    # Intentional single quote to find a keyword that starts with '$'
-    # shellcheck disable=SC2016
-    mapfile -t _keys < <(_paths_of_extends "${_content}") || _keys=()
-    for i in "${_keys[@]}"; do
-      local _next
-      _next="$(mktemp_with_content "$(jq ".|del(${i})" "${_cur}")")"
-      _cur="${_next}"
-    done
-    cat "${_cur}"
-  else
-    echo "${_content}"
-  fi
-}
+# shellcheck disable=SC1090
+# source = lib/json.sh
+source "${JF_BASEDIR}/lib/json.sh"
+# shellcheck disable=SC1090
+# source = lib/dependency.sh
+source "${JF_BASEDIR}/lib/dependency.sh"
+# shellcheck disable=SC1090
+# source = lib/helpers.sh
+source "${JF_BASEDIR}/lib/helpers.sh"
 
 function _expand_nodelevel_inheritances() {
   local _content="${1}" _validation_mode="${2}" _path="${3}"
@@ -108,6 +67,62 @@ function _expand_nodelevel_inheritances() {
   done
   perf "end"
   jq -r -c . "${_cur}"
+}
+
+function _expand_inheritances() {
+  local _nodeentry="${1}" _validation_mode="${2}" _jf_path="${3}"
+  local _materialized_file _content _jsonized_content _out _absfile
+  local -a _specifier
+  perf "begin: ${_nodeentry}"
+
+  mapfile -d ';' -t _specifier <<<"$(_normalize_nodeentry "${_nodeentry}" "${_jf_path}")"
+  _absfile="$(search_file_in "${_specifier[0]}" "${_jf_path}")"
+  _jsonized_content="$(jsonize "${_absfile}" "${_specifier[1]}" "$(join_by ';' "${_specifier[@]:2}")")"
+  # Fail on command substitution cannot be checked directly
+  # shellcheck disable=SC2181
+  [[ $? == 0 ]] || abort "Failed to convert a file:'${_absfile}' into to a json."
+  _materialized_file="$(mktemp_with_content "${_jsonized_content}")"
+  validate_jf_json "${_materialized_file}" "${_validation_mode}"
+  _content="${_jsonized_content}"
+  #----
+  if ! is_json "${_content}"; then
+    abort "Malformed JSON was given:'${_nodeentry}': _materialized_file='${_materialized_file}', _content='${_content}'"
+  fi
+  if is_object "${_content}"; then
+    local _tmp _local_nodes_dir _c _expanded
+    ####
+    # Strangely the line above does not causes a quit on a failure.
+    # Explitly check and abotrt this functino.
+    _c="$(expand_filelevel_inheritances "${_materialized_file}" "${_validation_mode}" "$(dirname "${_absfile}"):${_jf_path}")" ||
+      abort "File-level expansion failed for '${_nodeentry}'"
+    _tmp="$(mktemp_with_content "${_c}")"
+    _local_nodes_dir=$(materialize_local_nodes "${_tmp}")
+    expand_inheritances_of_local_nodes "${_local_nodes_dir}" \
+      "${_local_nodes_dir}:${_jf_path}"
+    _expanded="$(expand_nodelevel_inheritances "${_tmp}" \
+      "${_validation_mode}" \
+      "${_local_nodes_dir}:$(dirname "${_absfile}"):${_jf_path}")" ||
+      abort "Failed to expand node level inheritance for '${_nodeentry}'(3)"
+    _out=$(mktemp_with_content "${_expanded}")
+  else
+    : # Clear $?
+    _out="$(mktemp_with_content "${_content}")"
+  fi
+  cat "${_out}"
+  perf "end: ${_nodeentry}"
+}
+
+####
+#
+# Function intended to be used on 'script inheritance'.
+# Search for a file from an environment variable "_JF_PATH" and prints an absolute path of it if found.
+# In case it is not found, 1 will be returned.
+#
+# This function is indirectly called by 'jsonize' function through a command line it constructs
+#
+function find_file() {
+  local _target="${1}"
+  search_file_in "${_target}" "${_path}"
 }
 
 function _source_files() {
@@ -198,6 +213,15 @@ function _define_builtin_functions() {
   }
 }
 
+function export_names_for_script_inheritance() {
+  export -f find_file
+  export -f search_file_in
+  export -f abort
+  export -f message
+  export _JF_PATH
+  export _JF_PATH_BASE
+}
+
 function _render_text_node() {
   local _node_value="${1}"
   local _path="${2}" # DO NOT REMOVE: This local variable is referenced by built-in functions invoked on 'templating' stage.
@@ -241,32 +265,6 @@ function _render_text_node() {
   return "${_ret_code}"
 }
 
-function _paths_of_string_type() {
-  local _content="${1}"
-  echo "${_content}" | jq -r -c -L "${JF_BASEDIR}/lib" '#---
-import "shared" as shared;
-
-[paths(scalars_or_empty
-      |select(type=="string" and (startswith("eval:") or
-                                  startswith("template:"))))]
-              |sort
-              |sort_by(length)
-              |.[]
-              |shared::path2pexp(.)'
-}
-
-function _paths_of_extends() {
-  local _content="${1}"
-  echo "${_content}" | jq -r -c -L "${JF_BASEDIR}/lib" '#---
-import "shared" as shared;
-
-[paths(..)|. as $p|.[-1]|select(tostring=="$extends")|$p]
-              |sort
-              |sort_by(length)
-              |.[]
-              |shared::path2pexp(.)'
-}
-
 function _perform_templating() {
   local _content="${1}"
   local _ret="${_content}"
@@ -290,131 +288,6 @@ function _starts_with_templating_keyword() {
     return 0
   fi
   return 1
-}
-
-####
-#
-# Function intended to be used on 'script inheritance'.
-# Search for a file from an environment variable "_JF_PATH" and prints an absolute path of it if found.
-# In case it is not found, 1 will be returned.
-#
-# This function is indirectly called by 'jsonize' function through a command line it constructs
-#
-function find_file() {
-  local _target="${1}"
-  search_file_in "${_target}" "${_path}"
-}
-
-function export_names_for_script_inheritance() {
-  export -f find_file
-  export -f search_file_in
-  export -f abort
-  export -f message
-  export _JF_PATH
-  export _JF_PATH_BASE
-}
-
-function validate_jf_json() {
-  local _in="${1}" _mode="${2}"
-  if [[ "${_mode}" == "no" ]]; then
-    debug "validation skipped"
-    return 0
-  elif [[ "${_mode}" == "strict" ]]; then
-    _validate_jf_json_with "${_in}" "strict"
-  elif [[ "${_mode}" == "lenient" ]]; then
-    _validate_jf_json_with "${_in}" "lenient"
-  else
-    abort "Unknown validation mode:'${_mode}' was set."
-  fi
-  return $?
-}
-
-function dirof() {
-  local _target="${1}"
-  local _ret
-  _ret=$(dirname "$(readlink --canonicalize-missing "${_target}")")
-  echo "${_ret}"
-}
-
-function _encode_filename() {
-  local _filename="${1}" _dependency_space="${2}"
-  local _ret
-  _ret="${_JF_SESSION_DIR}/${_dependency_space}-$(hashcode "${_filename}").txt"
-  echo "${_ret}"
-}
-
-function _mark_as_in_progress() {
-  local _filename="${1}" _dependency_space="${2}"
-  local _encoded_filename
-  _encoded_filename="$(_encode_filename "${_filename}" "${_dependency_space}")"
-  touch "${_encoded_filename}"
-}
-
-function _unmark_as_in_progress() {
-  local _filename="${1}" _dependency_space="${2}"
-  local _encoded_filename
-  debug "check: unmark: '${_filename}'"
-  _encoded_filename="$(_encode_filename "${_filename}" "${_dependency_space}")"
-  rm "${_encoded_filename}" || {
-    message "WARN: ${_filename} was not found."
-  }
-}
-
-function _is_in_progress() {
-  local _filename="${1}" _dependency_space="${2}"
-  local _encoded_filename
-  _encoded_filename="$(_encode_filename "${_filename}" "${_dependency_space}")"
-  if [[ -e "${_encoded_filename}" ]]; then
-    debug "'${_filename}'(${_encoded_filename}) is in progress"
-    return 0
-  fi
-  debug "'${_filename}'(${_encoded_filename}) is NOT in progress"
-  return 1
-}
-
-function _check_cyclic_dependency() {
-  local _in="${1}" _dependency_space="${2}"
-  if _is_in_progress "${_in}" inheritance; then
-    abort "Cyclic ${_dependency_space} was detected on:'${_in}'"
-  else
-    debug "check: mark as in progress: '${_in}'"
-    _mark_as_in_progress "${_in}" inheritance
-  fi
-}
-
-function expand_filelevel_inheritances() {
-  local _materialized_file="${1}" _validation_mode="${2}" _path="${3}"
-  ####
-  # This is intentionally using single quotes to pass quoted path expression to jq.
-  # shellcheck disable=SC2016
-  local _in _cur _content
-  perf "begin:${_materialized_file}"
-  _in="${_materialized_file}"
-  _content="$(cat "${_in}")"
-  _cur="${_content}"
-  if is_object "${_content}"; then
-    # shellcheck disable=SC2016
-    # this is intentionally suppressing expansion to pass the value to jq.
-    if has_value_at '."$extends"' "${_content}"; then
-      local i
-      while IFS= read -r i; do
-        local _next _c _parent
-        _parent="$(expand_inheritances "$(_normalize_nodeentry "${i}" "${_path}")" "${_validation_mode}" "${_path}")"
-        _c="$(_merge_object_nodes "${_parent}" "${_cur}")"
-        # Cannot check the exit code directly because of command substitution
-        # shellcheck disable=SC2181
-        [[ $? == 0 ]] || abort "Failed to merge file:'${i}' with content:'${_cur}'"
-        _cur="${_c}"
-      done <<<"$(value_at '."$extends"[]' "${_content}")"
-    fi
-    local _cur_tmpfile
-    _cur_tmpfile="$(mktemp_with_content "${_cur}")"
-    jq -r -c '.|del(.["$extends"])' "${_cur_tmpfile}"
-  else
-    message "WARN: array expansion is not yet implemented."
-    echo "${_content}"
-  fi
-  perf "end:${_materialized_file}"
 }
 
 function materialize_local_nodes() {
@@ -467,8 +340,39 @@ function _sourced_files_dir() {
   echo "${_JF_SESSION_DIR}/source_files"
 }
 
-function _validate_jf_json_with() {
-  validate_json "${1}" "${_JF_SCHEMA_DIR}/${2}.json"
+function expand_filelevel_inheritances() {
+  local _materialized_file="${1}" _validation_mode="${2}" _path="${3}"
+  ####
+  # This is intentionally using single quotes to pass quoted path expression to jq.
+  # shellcheck disable=SC2016
+  local _in _cur _content
+  perf "begin:${_materialized_file}"
+  _in="${_materialized_file}"
+  _content="$(cat "${_in}")"
+  _cur="${_content}"
+  if is_object "${_content}"; then
+    # shellcheck disable=SC2016
+    # this is intentionally suppressing expansion to pass the value to jq.
+    if has_value_at '."$extends"' "${_content}"; then
+      local i
+      while IFS= read -r i; do
+        local _c _parent
+        _parent="$(expand_inheritances "$(_normalize_nodeentry "${i}" "${_path}")" "${_validation_mode}" "${_path}")"
+        _c="$(_merge_object_nodes "${_parent}" "${_cur}")"
+        # Cannot check the exit code directly because of command substitution
+        # shellcheck disable=SC2181
+        [[ $? == 0 ]] || abort "Failed to merge file:'${i}' with content:'${_cur}'"
+        _cur="${_c}"
+      done <<<"$(value_at '."$extends"[]' "${_content}")"
+    fi
+    local _cur_tmpfile
+    _cur_tmpfile="$(mktemp_with_content "${_cur}")"
+    jq -r -c '.|del(.["$extends"])' "${_cur_tmpfile}"
+  else
+    message "WARN: array expansion is not yet implemented."
+    echo "${_content}"
+  fi
+  perf "end:${_materialized_file}"
 }
 
 function expand_inheritances() {
@@ -485,49 +389,6 @@ function expand_inheritances() {
   cat "${_caching_filename}"
   _unmark_as_in_progress "${_norm_nodeentry}" inheritance
   perf "end: ${_nodeentry} (cached in ${_caching_filename})"
-}
-
-function _expand_inheritances() {
-  local _nodeentry="${1}" _validation_mode="${2}" _jf_path="${3}"
-  local _materialized_file _content _jsonized_content _out _absfile
-  local -a _specifier
-  perf "begin: ${_nodeentry}"
-
-  mapfile -d ';' -t _specifier <<<"$(_normalize_nodeentry "${_nodeentry}" "${_jf_path}")"
-  _absfile="$(search_file_in "${_specifier[0]}" "${_jf_path}")"
-  _jsonized_content="$(jsonize "${_absfile}" "${_specifier[1]}" "$(join_by ';' "${_specifier[@]:2}")")"
-  # Fail on command substitution cannot be checked directly
-  # shellcheck disable=SC2181
-  [[ $? == 0 ]] || abort "Failed to convert a file:'${_absfile}' into to a json."
-  _materialized_file="$(mktemp_with_content "${_jsonized_content}")"
-  validate_jf_json "${_materialized_file}" "${_validation_mode}"
-  _content="${_jsonized_content}"
-  #----
-  if ! is_json "${_content}"; then
-    abort "Malformed JSON was given:'${_nodeentry}': _materialized_file='${_materialized_file}', _content='${_content}'"
-  fi
-  if is_object "${_content}"; then
-    local _tmp _local_nodes_dir _c _expanded
-    ####
-    # Strangely the line above does not causes a quit on a failure.
-    # Explitly check and abotrt this functino.
-    _c="$(expand_filelevel_inheritances "${_materialized_file}" "${_validation_mode}" "$(dirname "${_absfile}"):${_jf_path}")" ||
-      abort "File-level expansion failed for '${_nodeentry}'"
-    _tmp="$(mktemp_with_content "${_c}")"
-    _local_nodes_dir=$(materialize_local_nodes "${_tmp}")
-    expand_inheritances_of_local_nodes "${_local_nodes_dir}" \
-      "${_local_nodes_dir}:${_jf_path}"
-    _expanded="$(expand_nodelevel_inheritances "${_tmp}" \
-      "${_validation_mode}" \
-      "${_local_nodes_dir}:$(dirname "${_absfile}"):${_jf_path}")" ||
-      abort "Failed to expand node level inheritance for '${_nodeentry}'(3)"
-    _out=$(mktemp_with_content "${_expanded}")
-  else
-    : # Clear $?
-    _out="$(mktemp_with_content "${_content}")"
-  fi
-  cat "${_out}"
-  perf "end: ${_nodeentry}"
 }
 
 function perform_templating() {
@@ -609,7 +470,6 @@ function main() {
 
 _JF_CWD="${JF_CWD:-"$(pwd)"}"
 _JF_BASEDIR="${JF_BASEDIR}"
-_JF_SCHEMA_DIR="${_JF_BASEDIR}/schema"
 _JF_PATH_BASE=${JF_PATH_BASE:-""}
 _JF_PATH=$(_mangle_path "${JF_PATH:-"."}" "${_JF_PATH_BASE}")
 _JF_TEMPLATING_ENABLED=${JF_TEMPLATING_ENABLED:-"yes"}
@@ -641,6 +501,8 @@ if [[ -n "${_JF_PATH_BASE}" ]]; then
 fi
 export_names_for_script_inheritance
 export _JF_POOL_DIR
+export _JF_SCHEMA_DIR
 _JF_POOL_DIR="$(nodepool_prepare _nodepool_expand_inheritances)"
+_JF_SCHEMA_DIR="${_JF_BASEDIR}/schema"
 
 main "${@}"
