Improve control flow on validation errors

diff --git a/jq-front b/jq-front
--- a/jq-front
+++ b/jq-front
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-set -eu
+set -Eeu
 
 JF_BASEDIR=$(dirname "$(readlink --canonicalize "${0}")")
 export JF_BASEDIR
@@ -111,7 +111,9 @@ function _validate_jf_json_with() {
   local _out=
   {
     _out=$(ajv validate -s "${_JF_SCHEMA_DIR}/${_mode}.json" -d "${_in}" 2>&1)
-  } || abort "Validation for '${_in}' was failed:\n${_out}"
+  } || {
+    quit "Validation by ajv for '${_in}' was failed:\n${_out}"
+  }
 }
 
 function find_file_in_path() {
@@ -162,13 +164,13 @@ function validate_jf_json() {
   if [[ "${_mode}" == "no" ]]; then
     return 0
   elif [[ "${_mode}" == "strict" ]]; then
-    _validate_jf_json_with "${_in}" "strict" || return 1
+    _validate_jf_json_with "${_in}" "strict"
   elif [[ "${_mode}" == "lenient" ]]; then
-    _validate_jf_json_with "${_in}" "lenient" || return 1
+    _validate_jf_json_with "${_in}" "lenient"
   else
-    message "Unknown validation mode:'${_mode}' was set."
-    exit 1
+    abort "Unknown validation mode:'${_mode}' was set."
   fi
+  return $?
 }
 
 function dirof() {
@@ -189,10 +191,11 @@ function expand_filelevel_inheritances() {
   # shellcheck disable=SC2016
   local _cur
   local _content
-  _in="$(find_file_in_path "${_target}" "${_path}")" || quit "${_target} was not found in ${_path}"
-  debug "validating ${_in}"
-  validate_jf_json "${_in}" "${_validation_mode}" || abort "Validation failed:${_in}:content='$(cat "${_in}")'"
-  debug "...validated"
+  _in="$(find_file_in_path "${_target}" "${_path}")"
+  message "validating ${_in}"
+  validate_jf_json "${_in}" "${_validation_mode}"
+  [[ $? == 0 ]] || abort "Failed to process '${_target}'"
+  message "...validated"
   _content="$(cat "${_in}")"
   _cur="$(mktemp_with_content "${_content}")"
   if [[ $(is_object "${_content}") == true ]]; then
@@ -298,6 +301,7 @@ function run_jqfront() {
     local _private_nodes_dir
     local _c
     _c="$(expand_filelevel_inheritances "${_target}" "${_validation_mode}" "${_jf_path}")"
+    [[ $? == 0 ]] || abort "File-level expansion failed for '${_target}'"
     _tmp="$(mktemp_with_content "${_c}")"
     _private_nodes_dir=$(materialize_private_nodes "${_tmp}")
     expand_inheritances_of_private_nodes "${_private_nodes_dir}" \
