Issue-#83: Introduce Node Pool mechanism (WIP)

diff --git a/jq-front b/jq-front
--- a/jq-front
+++ b/jq-front
@@ -430,7 +430,7 @@ function _encode_filename() {
   local _filename="${1}"
   local _dependency_space="${2}"
   local _ret
-  _ret="${_JF_SESSION_DIR}/${_dependency_space}-$(echo "${_filename}" | md5sum | cut -f 1 -d ' ').txt"
+  _ret="${_JF_SESSION_DIR}/${_dependency_space}-$(hashcode "${_filename}").txt"
   echo "${_ret}"
 }
 
@@ -568,12 +568,94 @@ function expand_inheritances_of_private_nodes() {
   debug "end:   expand_inheritances_of_private_nodes"
 }
 
+function _nodepool_expand_inheritances() {
+  local _nodeentry="${1}"
+  local _validation_mode="${2}"
+  local _path="${3}"
+  local _content _out _absfile _processor _args _ret
+  local -a _specifier
+
+  mapfile -t -d ';' _specifier <<<"${_nodeentry};;"
+  _absfile="$(_locate_file "${_specifier[0]}" "${_path}")"
+  _processor="${_specifier[1]}"
+  _args="${_specifier[2]}"
+
+  perf "begin: ${_nodeentry}"
+  _absfile="$(find_file_in_path "${_absfile}" "${_path}")"
+  # Fail on command substitution cannot be checked directly
+  # shellcheck disable=SC2181
+  [[ $? == 0 ]] || abort "Failed to find a file '${_absfile}'."
+  # Update _path to be able to find a file placed in the same directory as _absfile's
+  _path="$(dirof "${_absfile}"):${_path}"
+  _content="$(cat "${_absfile}")"
+  _content="$(jsonize "${_absfile}" "${_processor}" "${_args}")"
+  if ! is_json "${_content}"; then
+    abort "Malformed JSON was given:'${_nodeentry}'='${_content}'"
+  fi
+  if is_object "${_content}"; then
+    local _tmp _private_nodes_dir _c _expanded
+    ####
+    # Strangely the line below does not causes a quit on a failure.
+    # Explitly check and abotrt this functino.
+    _c="$(expand_filelevel_inheritances "${_absfile}" "${_validation_mode}" "${_path}")" ||
+      abort "File-level expansion failed for '${_absfile}'"
+    _tmp="$(mktemp_with_content "${_c}")"
+    _private_nodes_dir=$(materialize_private_nodes "${_tmp}")
+    expand_inheritances_of_private_nodes "${_private_nodes_dir}" \
+      "enabled" \
+      "${_private_nodes_dir}:${_path}"
+    _expanded="$(expand_nodelevel_inheritances "${_tmp}" "${_validation_mode}" "${_private_nodes_dir}:${_path}")" ||
+      abort "Failed to expand node level inheritance for file:'${_nodeentry}'(3)"
+    _out=$(mktemp_with_content "${_expanded}")
+  else
+    : # Clear $?
+    _out="$(mktemp_with_content "${_content}")"
+  fi
+  cat "${_out}"
+  perf "end: ${_nodeentry}"
+  #----------------------
+}
+
+function _jsonize_file() {
+  local _absfile="${1}" _processor="${2:-""}" _args="${3:-""}"
+  local _ret
+  if [[ ${_processor} == "" ]]; then
+    local _cmd="jq"
+    if [[ "${_absfile}" == *.yaml || "${_absfile}" == *.yml ]]; then
+      _cmd="yq"
+    fi
+    # Let the args split. Since it's args.
+    # shellcheck disable=SC2086
+    _ret="$(${_cmd} . ${_args} "${_absfile}")"
+  else
+    if [[ "${_processor}" == SOURCE ]]; then
+      # Only number of files matters and it's safe to use ls here.
+      # shellcheck disable=SC2012
+      cp "${_absfile}" "$(_sourced_files_dir)/$(ls "$(_sourced_files_dir)" | wc -l)"
+      _ret="{}"
+    else
+      export _path
+      _ret="$("${_processor}" "${_absfile}" ${_args} | jq .)"
+      unset _path
+    fi
+  fi
+  echo "${_ret}"
+}
+
+function _sourced_files_dir() {
+  echo "${_JF_SESSION_DIR}/source_files"
+}
+
+function _validate_jf_json_with() {
+  _validate_json "${1}" "${_JF_SCHEMA_DIR}/${2}.json"
+}
+
 function expand_inheritances() {
   local _filename="${1}"
   local _validation_mode="${2}"
   local _jf_path="${3}"
   local _caching_filename
-  _caching_filename="${_JF_POOL_DIR}/$(echo -n "${_filename}" | md5sum | cut -f 1 -d ' ')"
+  _caching_filename="${_JF_POOL_DIR}/$(hashcode "${_filename}")"
   perf "begin: ${_filename}"
   [[ -e "${_caching_filename}" ]] || {
     perf "expanding inheritances for file: '${_filename}'"
@@ -734,6 +816,6 @@ if [[ -n "${_JF_PATH_BASE}" ]]; then
 fi
 export_names_for_script_inheritance
 export _JF_POOL_DIR
-_JF_POOL_DIR="$(nodepool_prepare)"
+_JF_POOL_DIR="$(nodepool_prepare _nodepool_expand_inheritances)"
 
 main "${@}"
